DELETE FROM products;

INSERT INTO products (name, description, size, price, image, category) VALUES
('Anı 1/3', 'Rüyanın Hafızası ; Bu seri, sadece estetik bir yolculuk değil, aynı zamanda ruhun içsel haritasını okuma çabasıdır. Rüyalarda görülen tanıdık yerler, ilahi olana yaklaşan bilinç hâllerinin izdüşümüdür. Her resim, kendi içinde bir dua, bir tefekkür, bir içsel konuşmadır. Tanıdık yerler aslında hatırlanmayı bekleyen yönlerimizdir. Kendimize, Yaradan’a ve zamansız olana ait parçalar. Gidilmeli, keşfedilmeli ve bir anı olarak mekandan ayrılıp sonsuzluğa karışmalıdır.', '2960 x 3947 px', 299.99, 'img/anı.jpeg', 'store'),
('Git 2/3', 'Rüyanın Hafızası ; Bu seri, sadece estetik bir yolculuk değil, aynı zamanda ruhun içsel haritasını okuma çabasıdır. Rüyalarda görülen tanıdık yerler, ilahi olana yaklaşan bilinç hâllerinin izdüşümüdür. Her resim, kendi içinde bir dua, bir tefekkür, bir içsel konuşmadır. Tanıdık yerler aslında hatırlanmayı bekleyen yönlerimizdir. Kendimize, Yaradan’a ve zamansız olana ait parçalar. Gidilmeli, keşfedilmeli ve bir anı olarak mekandan ayrılıp sonsuzluğa karışmalıdır.', '2960 x 3947px', 199.99, 'img/git.jpeg', 'store'),
('Keşif 3/3', 'Rüyanın Hafızası ; Bu seri, sadece estetik bir yolculuk değil, aynı zamanda ruhun içsel haritasını okuma çabasıdır. Rüyalarda görülen tanıdık yerler, ilahi olana yaklaşan bilinç hâllerinin izdüşümüdür. Her resim, kendi içinde bir dua, bir tefekkür, bir içsel konuşmadır. Tanıdık yerler aslında hatırlanmayı bekleyen yönlerimizdir. Kendimize, Yaradan’a ve zamansız olana ait parçalar. Gidilmeli, keşfedilmeli ve bir anı olarak mekandan ayrılıp sonsuzluğa karışmalıdır.', '2960 x 3947px', 449.99, 'img/keşif.jpeg', 'store'),
('Hiç Bir Kamu Malına Zarar Verilmemiştir', 'Bu eser, doğduğum yer olan Mardin’in bugünkü turistik yüzünden çok, geçmişteki özgür, kendi halkına ait ve samimi zamanlarına duyduğum özlemi yansıtır. Surrealist bir yaklaşımla, hatıraların flu silüetleri ve taş duvarların gölgesinde kalan ruhu görünür kılmak istedim. Netliğini yitirmiş yapılar, artık yalnızca bellekte yaşayan bir aidiyetin izlerini taşırken, berrak gökyüzüyle örtüşen bu puslu manzara; bir şehrin, bir kimliğin sessiz çığlığıdır. Sol tarafta gölge gibi yazı ise imzamın yarısı, dede evime yazılmıştır şehrin en görünen yerlerinden birinde rahatsız edici büyüklükte fakat hayır, kamu malı zarar gormedi, batıda yargılayıp doğuda onların tarihi yapılarıyla kültür mastürbasyonu yaptığınız insanların özel alanı zarar gördü ve ihlal edildi.', '1152 x 2048px', 349.99, 'img/Hiç Bir Kamu malına zarar verilmemiştir.jpeg', 'store'),
('Çatı', 'Çatı, korunmaya alınmış bir kırılganlık ve gözlerin ardına gizlenmiş bir direncin cikabildigi en yüksekte olan halidir. eldeki kuş, hem özgürlüğün hem de incinmişliğin sembolüdür ve umudu sakince korur. Umut hep vardı. Sessiz ama sarsıcı bir varoluş çağrısıdır. Çatı șahitlik eder ki; hem kendini hem başkasını korumanın, hem de özgürlüğün sorumluluğunu taşımanın ifadesi oldukça zordur, yaşayan hisseder kimse anlatamaz ve kendini anlamanın kattığı deneyim paha biçilemezdir.', '2048 x 2048px', 599.99, 'img/çatı.jpeg', 'store'),
('O"nun İçin...?', 'Paranın suretine bürünmüş bir insan yüzü üzerinden onun kirli doğasını ve insanlık üzerindeki yıkıcı etkisini gözler önüne sermek istedim; gözlerden süzülen kanlı yaşlar, maddiyat uğruna dökülen acıların ve kaybolan maneviyatın yansımasıdır. Arka plandaki silik sözler ise, paranın gözünden konuşarak bizi onun karanlık gerçekliğiyle yüzleştirir, insanın para için neleri göze alabileceğine dikkat çeker. Oysa gerçek değer, görünmeyende, bilinçte ve içsel olanda gizlidir.', '2048 x 2048px', 249.99, 'img/onun için.jpeg', 'store'),
('Paket', 'Paket, suçlu portresinin üstündeli soyut ışık efektleriyle, toplumun dayattığı kimlik yargılarının ötesine geçerek bireyin içsel ışığını ve çok katmanlı varoluşunu vurguluyor; parçalanmış ve çoğunlukla kimyasal madde taşıyıcısı olan şeffaf paketlerle oluşturulan yüzün tamamını birleştirilerek bir araya gelmesi, hem kırılmış bir benliğe hem de yeniden inşa edilen kimliğe işaret ederken, kendi silahınla vurulmayı da anlatır. Işığın patlaması da geleceğe dair belirsiz ama saf bir umut, direniş ve dönüşümün sembolü olmuştur.', '50x70', 148.99, 'img/paket.jpeg', 'store'),
('İsim Konuşur', 'Bazen de somut ve maddi varlıklar, vizyon, eğitim, aile, ırk, kültür, kimlik, kadın, erkek, değil; İsim Konuşur. Silah formundadır ve konuşuluyorsa eğer öyledir. Sen ne kadar içeride, pakette veya kafeste de olsan merak etme çünkü bazen de isim konuşur.', '2048 x 2048px', 546.99, 'img/isim konuşur.jpeg', 'reference'),
('Paranoya', 'Paranoya, kişinin sürekli izlendiğini, yargılandığını ya da tehdit altında olduğunu düşünmesiyle karakterize edilen bir ruh hâlidir. Yaptığım kapakta yer alan çok sayıdaki göz, bireyin çevresi tarafından sürekli gözlemlendiği hissini temsil eder. Her bir göz; yargılayan, meraklı, kuşkulu ya da hissiz bakışları, yani farklı bakış açılarını simgeler. Yırtılmış kâğıt efektleri, yani kolaj tekniği; parçalanmış benliği ve bireyin zaman ile mekân algısındaki bozulmayı simgeler. Her bir göz resmi, farklı yaş ve insan tipi gruplarından alınmıştır. Paranoya sahibi bireyin gerçeklik algısı, tıpkı bu kolaj gibi, bütünlüğünü ve zaman algısını kaybetmiştir. Farklı duygular, düşünceler ve anılar iç içe geçerek birbirine karışır.', '2048 x 2046px', 867.99, 'img/paranoya.jpeg', 'reference'),
('Ağlamak için bir omuz.. ölmek için', 'Bu Kolaj kendi çektiğim resimler ile gördüğünüz her şeyi Ka’nın I Love parçasının derin duygularını, aidiyetle çelişen zorlukların ortasında filizlenen kardeşlik bağlarını ve sokaklara rağmen korunmuş saf sevgiyi yansıtır; bulanık camın ardından görülen Güngören semtinin ufak bir manzarası, geçmişe duyulan özlemi ve anıların silinmeyen izlerini taşıyan bir hafızayı temsil ediyor, burası herkesin giremediği bizim için “yuva” olan yerdir. Ötekidir ama yakından tanıyoruz.', 2693 x 1892px,111, 'img/ağlamak için bir omuz ölmek için.jpeg', 'reference'),
('Nixumandî', 'Yüzeyin kazındığı ve altta yatan tabakanın ortaya çıktığı grataj tekniğinde karıştırılmış akrilik ve yağlı pastellere sahip Mêrdîn dokuları, insanın derin gerçekliğini keşfetme süreciyle karşılaştırılabilir.', '21 x 15', 354.99, 'img/nixumandi.jpeg', 'reference'),
('Güneş', 'Kendi ile ilgilenen bir kadınla Kim ilgilenir? Güneş gibi davransan iyi olur Güneş hiçbir şey yapmaz ama Bir şey yapar Parlar Güneş her yere gider ama herkes için değil Ama en azından Hem Maldivlerde hem de Mêrdînde Hem Kaliforniyada hem de Camlıkahvede Birilerinin kalbinde, birilerinin yüzünde', '35 x 50', 777, 'img/güneş.jpeg', 'store'),
('Mükemmel Plan', 'Yüzeydeki katmanları kazımayı, bir bireyin iç dünyasına ulaşma ve dış görünümün ötesindeki özü anlama çabası olarak yorumlarım.', '21 x 15cm', 953, 'img/mükemmel plan.jpeg', 'reference'),
('Yüksek Son Teorisi', 'Ayrıca hatalar veya fazlalıklar gibi görünenleri temizleyerek güzelliği ve sadeliği ortaya çıkarma fikrini de taşır. Bu anlamda, grataj hem içsel bir arınmayı hem de kendini ifade etme yolculuğunu sembolize eder.', '21 x 15', 222, 'img/yüksek son teorisi.jpeg', 'reference'),
('Bana Bak', 'Dokulu kağıt üzerine Akrilik, marker kalem ve yağlı pasteller, Grataj tekniği ile uygulanmıştır. Grataj serisinin son resmi Bana Bak, kaotik fırça darbeleri ve kontrast renklerle izleyiciye dikkat çağrısı yaparken, içsel çığlıkları dışa vurur; parçalanmış formlar ve girdap gibi kıvrımlar, bastırılmış duyguların dışa vurumunu simgelerken, siyahın ağırlığı ve sarının patlamaları ruhsal çalkantı ve umut arasında gidip gelen bir zihin hâlini yansıtır, görünmek isteyen ama tam olarak anlaşılamayan bir benliğin görsel ifadesidir.', 666, 'img/bana bak.jpeg', 'reference');
